#!/usr/bin/env python3
"""
Regenerates fps_elf_blob.c from a built third_party/fps_elf/bin/fps_elf.elf.

fan_target ships the fps overlay ELF *embedded inside itself* so a single
fan_target.elf is the only file that needs to be deployed. On first launch,
main.c writes the embedded bytes out to /data/fan_target/fps_elf/fps_elf.elf
(once), then injects it into the running game on every launch after that.

Usage:
    python3 tools/gen_fps_elf_blob.py <path-to-fps_elf.elf> <output-dir>

If <path-to-fps_elf.elf> does not exist yet (fps_elf hasn't been built),
this writes a zero-length placeholder so main.c still compiles standalone.
main.c checks fps_elf_blob_len at runtime and skips deployment/injection
with a log message if it's 0, instead of failing to build.
"""
import sys
import os


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <fps_elf.elf> <output-dir>", file=sys.stderr)
        return 1

    src_path, out_dir = sys.argv[1], sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)
    c_path = os.path.join(out_dir, "fps_elf_blob.c")
    h_path = os.path.join(out_dir, "fps_elf_blob.h")

    if os.path.isfile(src_path):
        with open(src_path, "rb") as f:
            data = f.read()
        print(f"embedding {src_path} ({len(data)} bytes) -> {c_path}")
    else:
        data = b""
        print(f"WARNING: {src_path} not found yet; writing empty placeholder blob. "
              f"Build third_party/fps_elf first, then re-run this script.")

    with open(h_path, "w") as f:
        f.write(
            "/* Generated by tools/gen_fps_elf_blob.py -- do not edit by hand. */\n"
            "#pragma once\n"
            "#include <stddef.h>\n\n"
            "extern const unsigned char fps_elf_blob[];\n"
            "extern const unsigned int fps_elf_blob_len;\n"
        )

    with open(c_path, "w") as f:
        f.write("/* Generated by tools/gen_fps_elf_blob.py -- do not edit by hand. */\n")
        f.write('#include "fps_elf_blob.h"\n\n')
        f.write("const unsigned char fps_elf_blob[] = {\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            f.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        if not data:
            f.write("  0x00,\n")
        f.write("};\n")
        f.write(f"const unsigned int fps_elf_blob_len = {len(data)}u;\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
